### PR TITLE
Bump dependencies, switch to node16, and add simple smoke test

### LINKED ISSUE #4: Update to Node.js 16
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### PR DESCRIPTION
**Pull request by jirutka**
Resolves #4

### CODE REVIEW

**Comment by jirutka** [comment]
@adrians5j, can you please merge this?

**Comment by adrians5j** [comment]
Sorry @jirutka for the delay. I'll check this first thing in the morning.

**Comment by Moser-ss** [comment]
Hey @adrians5j do you have time to merge this PR?

**Comment by adrians5j** [comment]
Hey everybody,

first of all, sorry it took so long. Just super busy with everything, could not get myself to go over this PR and finally merge it. :/

In any case, it's merged. I bumped the version to 3.0.0, and update the docs to reflect that.

Hope it's fine.

Thanks again :)

**Pull request merged**
